# Generated by Django 3.0.5 on 2020-04-15 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negotiators', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='negotiator',
            options={'verbose_name': 'negotiator', 'verbose_name_plural': 'negotiators'},
        ),
    ]
